apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scp-keyvault-01
  labels: 
    azure.azureauthority.in: aks-apps
    app: asset-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: bc3f9031-885a-46ad-9fca-b1a28a1f08aa
    keyvaultName: kvproject3hanis
    objects:  |
      array:
        - |
          objectName: config
          objectType: secret
          objectAlias: config.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c